### ISSUE TITLE
Set up Javascript group capstone project with Kanban

### ISSUE THREAD

**Issue by diarisdiakite** [diarisdiakite/js-group-capstone#21]
https://github.com/diarisdiakite/js-group-capstone/projects/2
Team members: 2

**Comment by Gambit142** [comment]
Hi @diarisdiakite @As1imwe-Mark 👋, 

Good job so far!

## Highlights
- Created Kanban Board ✔️ 
- Every Project requirement is represented by a card ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️

- [ ] Kindly assign all cards to a member. Assigning cards to members helps the team know which member is responsible for building a feature and most times contains a detailed description of what that task is all about. 👍 💻 If a task is assigned, the avatar of the person(s) that the task was assigned to will be found in the bottom right corner of the card as shown in the screenshot below:

![image](https://github.com/lugard1/recipe/assets/77106962/0d2d950f-098b-4421-a3c6-7cadae91e6e3)

- [ ] After you assign all tasks to a member, it is important that the tasks are shared in an equal manner. Assigning tasks in an equal manner ensures that everyone is participating equally and nobody is overwhelmed with too many tasks. For example, you can assign all tasks for **_Team Member A_** to @diarisdiakite and all tasks for **_Team Member B_** to @As1imwe-Mark or the other way around. Then the group tasks can either be assigned equally to each team member or you assign them to both of you. 👍 😎 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Gambit142** [comment]
Hi @diarisdiakite @As1imwe-Mark 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban board ✔️ 
- Tasks are assigned and shared in an equal manner ✔️ 
- Information about team members is available ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
